Application:
    AbsolutePath: __DIR__/../../
    Backend: admin
    Acl:
        Token: ''
        CheckUserPermissions: true
        LogSystemApiTokenRequests: true
        LogUserRequests: true
    Logger:
        DisplayErrors: false
        Enabled: true
