Webiny:
    AbsolutePath: __DIR__/../../
    Backend:
        Path: /admin
    Acl:
        Token: ''
        CheckUserPermissions: true
        LogSystemApiTokenRequests: true
        LogUserRequests: true
        LogIncognitoRequests: false
    Logger:
        DisplayErrors: false
        Enabled: true
