Name: Core
Version: 0.1.0
Link: http://www.webiny.com/store/webiny/core/
Description: The Core app provides the essential functions for Webiny platform.

AuthorName: Webiny LTD
AuthorLink: http://www.webiny.com
AuthorEmail: info@webiny.com

Mailer:
    Default:
        CharacterSet: utf-8
        MaxLineLength: 78
        Priority: 2
        Sender:
            Email: pavel@getporthop.com
            Name: PortHop Team
        Transport:
            Type: smtp
            Host: email-smtp.eu-west-1.amazonaws.com
            Port: 465
            Username: AKIAJZHN6HBOYRZTQIBQ
            Password: Aqy0ZzCBDmquoBzInOAPSADRhcLGCgune2tsnJu2p3ng
            Encryption: ssl
            AuthMode: login
        AntiFlood:
            Threshold: 99
            Sleep: 1
        DisableDelivery: false

Storage:
    Services:
        Root:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../..
        Apps:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/..
        Temp:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../../Temp
        DevBuild:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../../public_html/build/development
        ProductionBuild:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../../public_html/build/production
        Files:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../../public_html/uploads
                        - __Application.WebPath__/uploads
                        - true
                        - true

Events:
    Core:
        Bootstrap:
            Request:
                - {Handler: Php/RequestHandlers/Api, Priority: 400}
                - {Handler: Php/RequestHandlers/Routes, Priority: 390}
        Api:
            Request:
                - {Handler: Php/Dispatchers/DiscoverDispatcher}
                - {Handler: Php/Dispatchers/EntityDispatcher}
                - {Handler: Php/Dispatchers/ServiceDispatcher}

Services:
    EntityFlowExport:
        Class: \Apps\Core\Php\Dispatchers\Flows\ExportFlow
        Tags: [entity-dispatcher-flow]

    EntityFlowCrudList:
        Class: \Apps\Core\Php\Dispatchers\Flows\CrudListFlow
        Tags: [entity-dispatcher-flow]

    EntityFlowCrudGet:
        Class: \Apps\Core\Php\Dispatchers\Flows\CrudGetFlow
        Tags: [entity-dispatcher-flow]

    EntityFlowCrudCreate:
        Class: \Apps\Core\Php\Dispatchers\Flows\CrudCreateFlow
        Tags: [entity-dispatcher-flow]

    EntityFlowCrudUpdate:
        Class: \Apps\Core\Php\Dispatchers\Flows\CrudUpdateFlow
        Tags: [entity-dispatcher-flow]

    EntityFlowCrudDelete:
        Class: \Apps\Core\Php\Dispatchers\Flows\CrudDeleteFlow
        Tags: [entity-dispatcher-flow]

    EntityFlowExecuteMethod:
        Class: \Apps\Core\Php\Dispatchers\Flows\ExecuteMethodFlow
        Tags: [entity-dispatcher-flow]

    SmartyExtension:
        Class: \Apps\Core\Php\View\SmartyExtension
        Tags: [Smarty.Extension]

    AnalyticsDb:
        Class: \Webiny\AnalyticsDb\AnalyticsDb
        Arguments:
            Mongo: @Mongo.Webiny