Name: Webiny
Version: dev-master
Link: https://github.com/Webiny/Webiny
Description: The Webiny app provides all the necessary platform features to develop new apps

AuthorName: Webiny LTD
AuthorLink: http://www.webiny.com
AuthorEmail: info@webiny.com

Marketplace:
    Api: https://beta.webiny.com/api

Storage:
    Services:
        Root:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        Config:
                            Directory: __DIR__/../..
        Apps:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        Config:
                            Directory: __DIR__/..
        Temp:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        Config:
                            Directory: __DIR__/../../Temp
                            Create: true
        DevelopmentBuild:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        Config:
                            Directory: __DIR__/../../public_html/build/development
        ProductionBuild:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        Config:
                            Directory: __DIR__/../../public_html/build/production
        Files:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        Config:
                            Directory: __DIR__/../../public_html/uploads
                            PublicUrl: __Application.WebPath__/uploads
                            DateFolderStructure: true
                            Create: true

Events:
    Webiny:
        Bootstrap:
            Request:
                - {Handler: Php/RequestHandlers/Api, Priority: 400}
                - {Handler: Php/RequestHandlers/Routes, Priority: 390}
        Api:
            Before:
                - {Handler: Php/RequestHandlers/ApiHandlers/ApiLogHandler, Priority: 500}
                - {Handler: Php/RequestHandlers/ApiHandlers/ApiCacheHandler::cacheRead}
            Request:
                - {Handler: Php/RequestHandlers/ApiHandlers/DiscoverHandler}
                - {Handler: Php/RequestHandlers/ApiHandlers/EntityHandler}
                - {Handler: Php/RequestHandlers/ApiHandlers/ServiceHandler}
            After:
                - {Handler: Php/RequestHandlers/ApiHandlers/ApiCacheHandler::cacheSave}
        User:
            Provide:
                - {Handler: Php/Lib/UserProvider/UserProviderEventHandler}
Services:
    DefaultEntityFlow:
        Class: \Apps\Webiny\Php\RequestHandlers\ApiHandlers\EntityFlows\DefaultEntityFlow
        Tags: [entity-flow]

    SmartyExtension:
        Class: \Apps\Webiny\Php\View\SmartyExtension
        Tags: [Smarty.Extension]

    AnalyticsDb:
        Class: \Webiny\AnalyticsDb\AnalyticsDb
        Arguments:
            Mongo: "@Mongo.Webiny"
    Hrc:
        Class: \Webiny\Hrc\Hrc
        Arguments:
            CacheRules: []
            CacheStorage:
                Object: \Webiny\Hrc\CacheStorage\Mongo
                ObjectArguments: ["@Mongo.Webiny"]
            IndexStorage:
                Object: \Webiny\Hrc\IndexStorage\Mongo
                ObjectArguments: ["@Mongo.Webiny"]