Platform:
    WebPath: http://sandbox.loc
    ApiPath: http://api.sandbox.loc
    AbsPath: __DIR__/../
    UploadsAbsPath: __DIR__/../Public/Uploads
    UploadsWebPath: http://sandbox.loc/Uploads
    AppsPath: __DIR__/../Apps
    AppsWebPath: http://sandbox.loc/Apps
    Backend:
        Prefix: admin
    Error:
        Reporting: true
    Bootstrap:
        App: Core
        Module: Layout
        Component: Layout

Database:
    Host: 127.0.0.1:27017
    Name: webiny-platform

Mongo:
    Services:
        Webiny:
            Class: \Webiny\Component\Mongo\Mongo
            Arguments:
                Host: 127.0.0.1:27017
                Database: webiny-platform
    ResultClass: \Webiny\Component\Mongo\MongoResult

Entity:
    Database: Webiny

Rest:
    Api:
        CompilePath: __DIR__/../Cache/Rest
        Environment: development
        Router:
            Class: \Apps\{app}\{module}\Php\Services\{service}
            Path: /{app}/{module}/{service}

Services:
    Smarty:
        Factory: \Webiny\Platform\Tools\TemplateEngine
        Method: getInstance

TemplateEngine:
    Engines:
        Smarty:
            ForceCompile: true
            CacheDir: __DIR__/../Cache/Smarty/Cache
            CompileDir: __DIR__/../Smarty/Compile
            TemplateDir: __DIR__/../Public
            AutoEscapeOutput: false
            MergeCompiledIncludes: false

Storage:
    Services:
        Root:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\Local
                    ObjectArguments:
                        - __DIR__/../
        Apps:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\Local
                    ObjectArguments:
                        - __DIR__/../Apps